### ISSUE TITLE
badges list command locks up badge bot when run twice

### ISSUE THREAD

**Issue by aBlender** [thoughtstem/badge-bot#1]
The error mentions "Too many open files" and references with-output-to-file: cannot open output file path: /home/bots/badge-bot/logs/log

I tried commenting out some logs from discord-bot, but I think I still got a too many open files error from accessing badges/earned files.

```
, (TOP (html (head (title Servlet Error) (link (@ (rel stylesheet) (href /error.css)))) (body (div (@ (class section)) (div (@ (class title)) Exception) (p The application raised an exception with the message: (pre with-output-to-file: cannot open output file
   path: /home/bots/badge-bot/logs/log
   system error: Too many open files; errno=24)) (p Stack trace: (pre handle-cmd at:
   line 36, column 0, in file /home/bots/badge-bot/server.rkt
 <unknown procedure> at:
   line 375, column 33, in file /usr/share/racket/collects/racket/contract/private/arrow-higher-order.rkt
 <unknown procedure> at:
   line 486, column 18, in file /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt
 <unknown procedure> at:
   line 375, column 33, in file /usr/share/racket/collects/racket/contract/private/arrow-higher-order.rkt
 <unknown procedure> at:
   line 486, column 18, in file /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt
 <unknown procedure> at:
   line 375, column 33, in file /usr/share/racket/collects/racket/contract/private/arrow-higher-order.rkt
 <unknown procedure> at:
   line 63, column 2, in file /usr/share/racket/pkgs/web-server-lib/web-server/dispatchers/dispatch-servlets.rkt
 select-handler/no-breaks at:
   line 163, column 2, in file /usr/share/racket/collects/racket/private/more-scheme.rkt
 connection-loop at:
   line 144, column 4, in file /usr/share/racket/pkgs/web-server-lib/web-server/private/dispatch-server-with-connect-unit.rkt
))))))
```

**Comment by srfoster** [comment]
I'll look at it now.

**Comment by srfoster** [comment]
I can't reproduce this on any of the following:

```
badges list name 0
```

```
badges list images 0
```

```
badges list @stephen 
```

```
badges graph
```

What's the exact command you're using to trigger the error?  And is it reliably reproducible or intermittent?

**Comment by aBlender** [comment]
We can never get `!badges list @name` to work more than once.  Badges graph always works as long as badges list hasn't been run. Once the error shows up once, all commands stop working.

![image](https://user-images.githubusercontent.com/10148840/86047665-1436e980-ba04-11ea-8b96-44b595035c60.png)

**Comment by aBlender** [comment]
So maybe it errors AFTER the 2nd time? It could also be different if you run it on different users. We haven't tested any of the images or names options. We've only used `!badges list @mention`.

Btw, you can see in the discord the error messages in the topics channels and core-staff-chat that came up after you ran badges list.

**Comment by srfoster** [comment]
Okay, that helps.

**Comment by srfoster** [comment]
I made a change to `discord-bot`: https://github.com/thoughtstem/discord-bot/issues/2

Let me know if that helps.

**Comment by aBlender** [comment]
Ok, it works now. Thank you.
