### ISSUE TITLE
Award command is not working for a new accounts

### ISSUE THREAD

**Issue by aBlender** [thoughtstem/badge-bot#2]
Looks like the bot isn't creating a new file new students. The award command still works for existing students though.

![image](https://user-images.githubusercontent.com/10148840/86058444-c3c88780-ba15-11ea-9cf2-7d21fff282ed.png)

**Comment by srfoster** [comment]
Okay, should be fixed with: https://github.com/thoughtstem/discord-bot/commit/a690da105d19d48bd82159f3e8cc2ed30023fab7
